### ISSUE TITLE
400 Bad Request when configured locally for IP address other than 127.0.0.1

### ISSUE THREAD

**Issue by masterlid** [martenframework/marten#100]
If configured at **config/settings/development.cr** to serve for IP address other than 127.0.0.1 (127.0.0.3 for instance) Marten always responds as "400 Bad Request". Port number has no matter.

**Comment by ellmetha** [comment]
Hey! 👋 

Thanks for raising this!

This happens because of the [HTTP Host Header protection](https://martenframework.com/docs/security/introduction#http-host-header-attacks-protection). In order to use `127.0.0.3` as a host in development, you would need to configure the [`allowed_hosts`](https://martenframework.com/docs/development/reference/settings#allowed_hosts) setting accordingly:

```crystal
Marten.configure do |config|
  config.allowed_hosts = ["127.0.0.3"]
end
```

It should be noted that Marten automatically sets this setting to `[".localhost", "127.0.0.1", "[::1]"]` in debug mode (which accounts for most development use cases I believe).

Another point to note is that the error returned in development in the v0.2 of Marten was clearly unhelpful and this behavior was actually improved as part of #76 to return a proper server error allowing to better understand what was going on. This means that with the upcoming release (v0.3) it'll be easier to identify why this error happens and how to fix it.

I'll close this issue in the meantime given that this was already tackled as part of #76!
