### ISSUE TITLE
Invalid email/password - tell the user which

### ISSUE THREAD

**Issue by notramo** [martenframework/marten#191]
In the case of invalid email/password, the generated auth does not tell the user what is incorrect: the email or the password. This is bad UX and has no security improvement.

https://kevin.burke.dev/kevin/invalid-username-or-password-useless/

Also, in the current auth implementation, the hashing function only runs if the email is found in the database. If the email is not registered, the 422 error is returned immediately, however, if it's registered, the password is hashed and compared first, which **adds a significant delay**, so it's very easy to figure out from the login page, without even going to the registration page.

**Comment by ellmetha** [comment]
@notramo this is not a bug - can you please use this label sparingly?

Anyway, I am going to mark this issue as a "Won't fix" as I don't think altering this aspect changes much in the grand scheme of things, and I actually tend to think that it's better to use a generic error in these situations even if it's less ideal from a UX standpoint. This is also something that a lot of security guidelines mention (like [OWASM auth cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-responses)).

I acknowledge that some projects may want something different and that the generated authentication is opinionated. At the same time, the idea is that once it's generated, it's part of the project and can be modified easily: from there, it is very easy for developers to just alter the schema validation logic of the generated `auth` app and modify the auth process so that it suits their needs and requirements. Marten will never account for all possible authentication requirements and preferences, developers can simply use the generated auth as a starting point and add or modify things from there.
