### ISSUE TITLE
URL, in templates, cannot reference non-handler route definitions

### ISSUE THREAD

**Issue by igbanam** [martenframework/marten#242]
With this root routes file

```crystal
Marten.routes.draw do
  path "/nested-app", NestedApp::ROUTES, name: "nested_app"
end
```

A template file cannot reference this route using `{% url "nested_app" %}`. However, if it points to a handler, like in the example below

```crystal
Marten.routes.draw do
  path "/nested-app", NestedApp::ROUTES, name: "nested_app"
  path "/direct-to-handler", DirectHandler, name: "direct"
end
```

Then `{% url "direct" %}` properly compiles into `"/direct-to-handler"`.

I expect that with the nested routes, the same behaviour should hold?

**Comment by ellmetha** [comment]
Hey! 👋 

Your `nested_app` route is an [including route](https://martenframework.com/docs/handlers-and-http/routing#defining-included-routes) and as such it does not map to a concrete handler: only concrete handler routes can be resolved using the `url` template tag.

I imagine your `NestedApp::ROUTES` constant contains another route map, so instead of trying to resolve `nested_app` you should probably try to resolve the route of one of the underlying (namespaced) routes (eg. `{% url "nested_app:sub_route" %}`).
