### ISSUE TITLE
`.` is not allowed in route names

### ISSUE THREAD

**Issue by notramo** [martenframework/marten#98]
Is there a reason `.` is not allowed in route names? It would enable naming routes like `photos.index`.

**Comment by ellmetha** [comment]
Hey @notramo! 👋

Thanks for reporting this. I don't see any reason to prevent this indeed, and this is definitely something that we can fix.

I see that your route name is `photos.index`. Do you know that you can define "namespaces" for routes by using [included routes](https://martenframework.com/docs/handlers-and-http/routing#defining-included-routes)? I'm mentioning this because for your use case, it looks like you could resolve your routes using `photos:index` if you had a `photos` route mapping to photo-related sub-routes (for example).

**Comment by notramo** [comment]
I didn't know about included routes. It fits the use case indeed, however, there may be some use cases where the dot notation can be helpful.
